apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: paperless-ng
version: 1.0.21
appVersion: "1.5.0"
description: Paperless-ng is an application by Daniel Quinn and contributors that indexes your scanned documents.
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/charts/stable/paperless-ng
icon: https://truecharts.org/_static/img/appicons/paperless-ng-icon.png
keywords:
  - paperless-ng
sources:
  - https://hub.docker.com/r/linuxserver/paperless-ng
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.16.0
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 6.0.69
- condition: redis.enabled
  name: redis
  repository: https://truecharts.org
  version: 1.0.76
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - incubator
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
